[package]
name = "RustSeek"
version = "0.1.0"
edition = "2021"



[dependencies]
ignore = "0.4"
num_cpus = "1.13"
rayon = "1.5"
zip = "0.5"
termcolor = "1.2"
dialoguer = "0.10.0"
indicatif = "0.17.8"
rand = "0.9.0-alpha.1"
terminal-emoji = "0.4.1"
crossterm = "0.26.1"